### ISSUE TITLE
Request to Implement Version Tagging `v1.00`

### ISSUE THREAD

**Issue by seanconroy2021** [chmeliik/checkton#12]
Hi 👋 ,

I appreciate the work you've done on this project. Could you please start tagging versions of the action? I want to add this action to a repo, but I need to tag it to a specific version to ensure there are no breaking changes.

It could be done manually tagging or using this action: [action-gh-release](https://github.com/softprops/action-gh-release) which in my view is a better option. If you want, I can create a fork and implement whichever one you choose. Sorry to be annoying you.

Thank you!
Sean

**Comment by chmeliik** [comment]
Absolutely :+1: 

I'm planning to pre-build the [image](https://github.com/chmeliik/checkton/blob/017c7bfe36425c54c279d1a399f2d84fa78b5ce1/action.yaml#L53) so that your workflow doesn't have to build it again every time. Once I have that figured out, I want to start versioning this action.

Thanks for the pointer to action-gh-release, I'll check it out

**Comment by seanconroy2021** [comment]
Thanks for the update, @chmeliik! I'll keep my PR in WIP until the repo is moved. 
I really appreciate the update 😄
